version: "3"

volumes:
  mysql_data:

services:
  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${NEXT_CONTAINER_NAME_DEV}
    volumes:
      - "./frontend/thesis-next:/app"
    command: sh -c "yarn install && yarn dev"
    ports:
      - ${NEXT_PORT_DEV}:3000
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_ENV=${NEXT_ENV_DEV}
    tty: true
    stdin_open: true
    networks:
      - front-tier

  go:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: ${GO_CONTAINER_NAME_DEV}
    volumes:
      - ./backend:/go/src/app
    environment:
      - "TZ=Asia/Tokyo"
      - GOLANG_ENV=${GO_ENV_DEV}
    env_file:
      - ./mysql/.env
    ports:
      - ${GO_PORT_DEV}:8080
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
    networks:
      - front-tier
      - back-tier

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: ${DB_CONTAINER_NAME_DEV}
    tty: true
    stdin_open: true
    env_file:
      - ./mysql/.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default-time-zone=Asia/Tokyo
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - ${DB_PORT_DEV}:3306
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
    name: front-tier
  back-tier:
    driver: bridge
    name: back-tier
